[package]
version = "0.1.0"

title = "MF MPCDI converter"
description="Brings the support of MPCDI videoprojector files."
authors = ["Moment Factory","Antoine Pilote"]

readme  = "docs/README.md"
changelog="docs/CHANGELOG.md"
repository = "https://github.com/MomentFactory/Omniverse-MPCDI-converter"

category = "Simulation"
keywords =  ["videoprojector", "MPCDI", "audiovisual", "video", "projection", "videomapping"]

preview_image = "data/preview.png"
icon = "data/mf-ov-extensions-icons.png"

[dependencies]
"omni.kit.uiapp" = {}

[[python.module]]
name = "mf.ov.mpcdi_converter"
