[package]
version = "1.1.1"

title = "MF MPCDI converter"
description="Brings the support of MPCDI videoprojector files."
authors = ["Moment Factory","Antoine Pilote"]

readme  = "docs/README.md"
changelog="docs/CHANGELOG.md"
repository = "https://github.com/MomentFactory/Omniverse-MPCDI-converter"

category = "Simulation"
keywords =  ["videoprojector", "MPCDI", "audiovisual", "video", "projection", "videomapping"]

preview_image = "data/preview.png"
icon = "data/mf-ov-extensions-icons.png"

toggleable = false

[core]
reloadable = false
# Load at the start, load all schemas with order -100 (with order -1000 the USD libs are loaded)
order = -100


[dependencies]
"omni.kit.uiapp" = {}
"omni.kit.tool.asset_importer" = {}

[[python.module]]
name = "mf.ov.mpcdi_converter"

[package.target]
kit = ["105.1"]

[package.writeTarget]
kit = true
python = false
