[package]
# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Lists people or organizations that are considered the "authors" of the package.
authors = ["Moment Factory","Antoine Pilote"]

# The title and description fields are primarily for displaying extension info in UI
title = "MF MPCDI converter"
description="Brings the support of MPCDI videoprojector files."

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# URL of the extension source repository.
repository = "https://github.com/MomentFactory/Omniverse-MPCDI-converter"

# One of categories for UI.
category = "Simulation"

# Keywords for the extension
keywords =  ["videoprojector", "MPCDI", "audiovisual", "video", "projection", "videomapping"]

# Location of change log file in target (final) folder of extension, relative to the root.
# More info on writing changelog: https://keepachangelog.com/en/1.0.0/
changelog="docs/CHANGELOG.md"

# Preview image and icon. Folder named "data" automatically goes in git lfs (see .gitattributes file).
# Preview image is shown in "Overview" of Extensions window. Screenshot of an extension might be a good preview image.
preview_image = "data/preview.png"

# Icon is shown in Extensions window, it is recommended to be square, of size 256x256.
icon = "data/mf-ov-extensions-icons.png"

# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}

# Main python module this extension provides, it will be publicly available as "import mf.ov.mpcdi_converter".
[[python.module]]
#TODO mf.ov.mpcdi_converter
name = "mf.ov.mpcdi_converter"

[[test]]
# Extra dependencies only to be used during test run
dependencies = [
    "omni.kit.ui_test" # UI testing extension
]
